TotalWarRomeIIGreetings = [
    'In the names of our people and our gods, greetings to our honoured friends!',
    'I came to unlock my word-hoard, and share wisdom at your table and, perhaps, reach agreement.',
    'Greetings! May our mighty gods lend wisdom to my speech, and patience to your hearing!',
    'You are most worthy for listening to my words, spoken in hope, for my people.',
    'I bring the blessings of my gods and my people. All look favourably upon you today.',
    'May the gods bless your patience and give me words that will gain your agreement.',
    'You honour me with your attention. I hope my words will be heard with kindness.',
    'I am thankful that I have your ear, and hope that I can speak the right words to please you.',
    'I have been chosen by my people as a tongue for their words. Hear me, then, with honesty…',
    'Greetings and blessings of my ancestors! I have much to say, if you will but listen…',
    'I am sent to speak to you, and hear words. I must have offended many gods to be given this reward!',
    'I’m am here with all the enthusiasm of a lame horse, buckling under unfair burden. Hear my words…',
    'I would sooner be filling my belly with good pork than bandying words! But speak I must!',
    'I am looking forward to a bellyful of ale once we are done, so I will speak plainly and quickly.',
    'Few among my people envy me today. And having smelled you, I begin to understand why…',
    'I am not known for a patient or kindly nature, so listen as I speak. And then agree!',
    'I like an axe or sword better than weak words, so you would do well to agree today!',
    'I come to give of my word-hoard. Will you listen as I speak for my people and my gods?',
    'In the name of our people, greetings! I have words. And if the gods will it they are words of friendship.',
    'I greet you! May the Gods of Fellowship bless our meeting.',
    'I hope I am welcome here, and that my words find willing ears and wise hearts.',
    "The greetings of the gods to you. I carry my people's word-hoard, a gift for you.",
    'I ask only that you listen. I am the messenger for my people, and an honourable son of honoured ancestors.',
    'I bring you word from our elders and wise women, crafted in good faith, and delivered with truthful tongue.',
    'I am to speak of agreements with you, honourably offered and honourably received.',
    'My people are not word wastrels. We speak to the point but, I hope, with honesty.',
    'If you would hear my words, then I speak with the voice of my people.',
    'May the gods smile on our meeting, that we may both profit by it!',
    'The blessings of the heavens to you and yours! Kindly give attention to my words, that all may profit!',
    'Greetings, in the name of my lord, and my own humble felicitations besides. May we speak together?',
    'Greetings  friend! I, as voice for my lord, humbly seek your most noble attention.',
    'I bring terms that I trust will be of keen interest to the ear of one so honourable and wise.',
    'Greetings, most honourable one! I wish for but a short time to explain the needs of my master.',
    'I search not for debate and discord, but for your most worthy attention.',
    'You honour me by your attention, worthy listener! I wish to speak of many matters…',
    "I thank you for receiving me, and for the attention you give to my lord's embassy.",
    'Pleasant greetings to you, worthy representative of a great people! I hope for your fleeting attention…',
    'In the name of my most dread lord, greetings. He sends me to speak in his mighty stead.',
    'Listen, for I speak in the name, and with the authority, of my most majestic and warlike lord!',
    'My most honourable lord and master bids me greet you as befit your station, and to speak in his name.',
    'I bring mighty words from my master, pregnant with god-granted wisdom. Listen carefully, and well!',
    'Greetings to you as befits your position. I speak the words of an honest lord. Listen well!',
    'I bring greetings from my most benevolent lord and will speak to you as long as this does him no disservice.',
    'I have words for the ears of the worthy. For the unworthy, I have only scant regard and less love!',
    'I am not here to debate, dissemble or over-haggle. I come seeking acceptance of proposals made.',
    "I speak only to gain your acceptance of my lord's offerings. You would do well to heed my words.",
    'I am the trusted voice of my lord and demand the attention of an honest audience.',
    'I come as an emissary, bringing greetings and a proposal to our mutual profit.',
    'Greetings! I come to speak for my master, and trust that the Gods will breathe wisdom into all who listen!',
    'I am sent by my master to speak on matters of some importance to us both.',
    'I welcome this chance to speak, for I think you will find what I say is of much interest…',
    'Greetings, friend. I bring a treasure of words that will surely find favour with your people.',
    'I seek acceptance for terms that will surely bring progress to all our lands.',
    'I speak the words of a master renowned for honesty and fair dealing. You are worthy of his words.',
    'I thank you for this audience. You should find the words I bring more than interesting.',
    'Well met! I speak, the devoted servant of my people, to one who we would name a friend.',
    'I seek acceptance on certain matters that could result in common gain for our peoples. Shall we begin?',
    'The people of Carthage send their blessings and greetings and hope that you will hear their words.',
    "The blessings of Ba'al Hammon be upon you. We have much to discuss.",
    'Greetings! I come to you as a humble friend hoping to share wise and honest words.',
    'I am here to offer terms that are both fair and just.',
    'Honoured friend! I pray that you will hear my words.',
    'I am pleased to see you, my friend! May we sit and talk awhile?',
    'I am the voice of the people of Carthage and I bring you their words.',
    'I would share words with you on matters of great import.',
    'Your honesty and virtue are well known in Carthage.',
    'I offer my words to your ears, and pray you find them to your liking.',
    'Listen. I have much to discuss with you.',
    'Mighty Carthage would have you hear my words.',
    'You will listen with rapt attention to my words.',
    'Hear me and fear the might of Carthage in my voice!',
    'We have much to discuss, so let us begin.',
    'The people of Carthage send word: you would do well to listen.',
    'I will be brief. We have matters to discuss.',
    'Greetings. Now, to the matter at hand…',
    'Listen very carefully. I shall say this only once.',
    'I will not waste breath on pleasantries with the likes of you.',
    'The people of Carthage extend the hand of friendship to you and yours.',
    'Carthage has matters to discuss with you. Will you listen?',
    'Greetings from mighty Carthage. I have a proposal I wish to discuss.',
    'I come to you with truth in my heart and a proposal on my lips.',
    'I am here to present terms, will you hear them?',
    'We have much to discuss, shall we begin?',
    'Greetings friend. I have matters I wish to discuss with you.',
    'The people of Carthage have sent me forth to share words with you.',
    "May the blessings of Ba'al Hammon be upon our discussions this day.",
    'I am a representative of the people of Carthage, my words are their words.',
    'I bring greetings to you, friend of Pharaoh, glory and wealth unto Him, and the blessings of His words.',
    'Greetings and blessings from the mouth of Pharaoh, the blessed of Maat, at this joyous meeting of friends!',
    'Blessings unto the worthy, given in the name of mighty Pharaoh, and greetings to our friends!',
    'I will speak fair words in the name of Pharaoh, Lord of the Two Egypts, so that agreement comes quickly.',
    'In the name of All-Wise Pharaoh, hail! Give gracious hearing to my mission.',
    'I speak with the voice of Pharaoh, the Merciful and Just, and bid you hear my words with kindness.',
    'May wisdom of Thoth be yours as you listen. So speaks my master, glorious Pharaoh!',
    'I would beg a little of your time to hear my unworthy embassy, although I speak but poorly.',
    'I have come with words from Pharaoh, the ornament of His people, to fill your ears with truth.',
    "In Pharaoh's name, health be His, I bring fair greetings, blessings, and words of honesty.",
    'On your knees as I speak the words of Pharaoh, glory and strength to Him, and give thanks for His wisdom!',
    'Tremble at the words of Pharaoh, mighty and terrible, as my  tongue gives voice for your unworthy ears!',
    'Greetings from my noble lord, Pharaoh of the Two Lands. I speak now with His voice, in honesty not flattery.',
    "I will speak with divine Pharaoh's voice, for His power encompasses all. You will listen with due diligence.",
    'Listen, for I speak for Pharaoh, master of sky and earth! I give voice to His majesty and truth!',
    "It is my part to speak according to divine Pharaoh's will. It is your part to listen respectfully.",
    'Pharaoh, great hunter of the Nile, does you a great honour by sending me, His humble servant, as an emissary.',
    'I speak the majestic and just words of mighty Pharaoh, heir to a lineage older than all others!',
    'Greetings and such felicitations as do honour to my master, Pharaoh, health and strength be ever His!',
    'I approach in the dread name of Pharaoh, strength be unto Him. My words are His words, and should have a hearing.',
    'Greetings from my divine lord, Pharaoh of the Two Egypts. I speak as His voice, and listen as His ears.',
    "Greetings, and the blessings of the river from cataract to delta! I come to serve at divine Pharaoh's order.",
    'Pharaoh, whose words bring joy to every ear, bids me give His greetings, and speak to you.',
    'Greetings, foreigner, in the name of glorious Pharaoh, the justice and master of Egypt.',
    'My lord Pharaoh, divinity in human flesh, wishes me to speak on his behalf concerning matters between our peoples.',
    'For Pharaoh, first among kings, greetings and blessings. We have much to discuss.',
    'The divine Pharaoh, in his majesty and holiness, sends blessings for our meeting, in the hope of a favourable outcome.',
    'Pharaoh, who is like unto the Gods, orders me to give you greetings, and to speak plainly of his desires.',
    'The Queen of Egypt gives you greetings - I come to speak plainly of my desires.',
    'I have words for worthy ears. For the unworthy, I have only scant regard and much less love!',
    'Well met! I, the devoted servant of my people, speak to one we would name a friend.',
    'The blessings of the gods be ours today. I ask only for ears willing to listen.',
    'I extend my royal greeting. Do you desire to hear a worthy proposal?',
    'May the gods of east and west bless this portentous meeting! Hear my words and decide!',
    'Greetings, most honourable one! Palmyra requires but a smidgen of your time, and your patience shall be repaid tenfold.',
    'Your willingness to listen brings joy and hope to my heart. This is my proposal...',
    'Greetings. This time, my salutations are accompanied by a demand. Listen well!',
    'We have a proposal for you. Consider your response carefully.',
    'I see you quiver... There is no need, I have come to you with a simple offer.',
    'I speak only wisdom, exalted and divine. Reject us at your own peril!',
    'Palmyra extends an honest and honourable offer to you. Do yourself a service and agree.',
    'I feel particularly lenient today, but your refusal to cooperate might yet furrow my brow. This is best avoided.',
    'What I offer today, I shall not tomorrow. Palmyra needs your answer and quickly!',
    'I bring you the gift of choice. Choose now and choose wisely!',
    'I humbly await an audience. Do not turn me away.',
    'Greetings! As rain brings life to the barren desert so will my words pour joy into your heart.',
    'Only you are worthy of my personal attention. My offer shall go to no other ruler, mighty as he may be.',
    'You are a trusted friend of Palmyra. It is to you alone that I bring the following proposal...',
    'Well met. I speak, the devoted servant of my people, to one who we would name a friend.',
    'Greetings! I bring word from my people to you, most noble and wise interlocutor.',
    'From my people, greetings and their prayers to Zeus for your continued good fortune. Now, to business…',
    'Salutations to you, and hopes that poets will long write of our meeting here today!',
    'I thank you for your attention. I trust we will find that harmony pleasing to the gods today.',
    'I feel the keen honour of addressing you today, so greetings, in the name of my people!',
    'I appeal for a kind hearing, for your reason and nobility is known throughout the world.',
    'You are known for wisdom and foresight, blessed by Athena herself. Therefore, give me your kind attention...',
    'I thank you for receiving my embassy. I will hope to sway you with the logic of my cause…',
    'Greetings! May all that I speak add to the dignity of our meeting, and find acceptance in you!',
    'I will speak with humble voice, though I speak for a proud people, and hope my words find acceptance.',
    'I am charged to speak honestly-- as if one of us would do otherwise! You would do well to listen.',
    'Hear my words! I come with proposals so wise that they might have been blessed by Athena herself.',
    'Hermes grant my words wings, that I may be done with this quickly. I have other business this day.',
    'The gods decree that we must speak with you in person. The gods have never met you, have they?',
    'I am here an unfortunate emissary, with terms for an unworthy audience. You should listen.',
    'Hello. HELLO. I. Come. To. Talk. Nod if you can understand me, dolt! O! Zeus give me strength!',
    'I fear my time is wasted but the gods care little for my convenience. Very well. Greetings!',
    'Greetings. I have words to speak, if you have ears for them. Am I going too quickly for you?',
    'I wish this occasion to pass with some haste. I will be honest: I do not care for your looks.',
    "Well, what do you want? No. That's wrong. Um... How to say... Greetings, in the name of my people!",
    'I bring the greetings and good wishes of my people. Let us reason together, in friendship I hope.',
    'I give thanks to Athena, for the wisdom that allowed this meeting to happen!',
    'The blessings of Zeus on you and yours! I would speak a few words with you, of benefit to all.',
    'You honour my people by this meeting. I trust I will repay that honour with honesty.',
    'I come as an honest emissary, to speak for my people as my ability allows, if you will listen.',
    'I greet you in the name of my people. Let us talk simply and with honesty.',
    'The blessings of the gods be yours and ours today. I ask only for willing ears to hear my speech.',
    'May Hermes give my words swift passage to your hearts and minds, so that we may have agreement!',
    'Greetings, honoured friend. I would speak now of honour, glory and other matters…',
    'Hermes give us speed! Athena give us wisdom! And then let us give our people cause for satisfaction!',
    'I have high hopes that you will see the sense in my proposition.',
    'Well met. Perhaps we may speak together after I have refreshed myself?',
    'Many speak highly of your sharp mind and farsightedness. I look forward to experiencing them.',
    "I advise you to listen to what I have to say, if you have your people's interests at heart.",
    'I come to you only after detailed consultation of the omens. Listen, consider, and act with wisdom.',
    'My time is precious but it is yours for now. I pray you will not waste it.',
    'The priests have read the guts of a sheep, and inform me that our meeting is propitious.',
    'The deal I am here to discuss favours us both.',
    'Let us speak together. Great deeds are not achieved without careful consideration.',
    'From the Senate and People of Rome, greetings to our noble friends, and words of great joy to come!',
    'Salutations and friendship from the Senate and People of Rome, and a proposal for your august consideration!',
    'In the name of Rome, honoured greetings unto you. I am sent to speak for the People and the Senate.',
    'Salutations and joyous greetings to you, honoured friend of Rome! I have words to speak.',
    'Greetings, good friend of Rome, greetings. Let us speak our parts and find agreement!',
    'Rome and the Senate graciously extend their greetings and good wishes. Now, to business.',
    'Your people are well known in Rome for honesty and manly virtue. That is why I have been sent.',
    'I wish to speak to you of matters of mutual benefit, although in truth, I think you benefit most!',
    'The Senate sends greetings to you, a most worthy diplomat for your people.',
    'I speak with the voice of the Senate, and am ordered to offer their felicitations at this meeting!',
    'The Senate send such greetings as do them no dishonour, and words for your unworthy ears.',
    'The Senate and People of Rome have charged me to deliver their proposal. I am not envied in this task.',
    'In the name of the Senate and People, I speak of worthy things to the unworthy.',
    'Hail. Heed now to the words of the wise Senate, and the rightly proud People, of Rome.',
    'I speak now with the dread voice of the Senate of Rome. Listen carefully, for my words have weight!',
    'I bring word from Rome to your ears. You would do well to grasp my full meaning.',
    'I come from Rome to do such honour as befits your station. So then, greetings.',
    'I will speak shortly as befits this meeting, and come to the business at hand. From Rome, greetings to you.',
    "I am but the Senate's servant in this matter, and speak only as I must: greetings to you and yours.",
    'Hail! The Senate and People of Rome send greetings and a proposal.',
    'In the name of the Rome, salutations! Let us speak as friends, and conclude any business in mutual satisfaction.',
    "In the Rome's name, greetings! I come, as an Senatorial servant, to seek answers to questions of mutual interest.",
    'I am sent by the Senate to request your attention in some small matters.',
    'Greetings from the Senate and People. I bring words that may bring joy to your ears.',
    'Hail! Rome greets you, and I am sent to speak on her behalf in many matters.',
    'From the Senate, greetings and respect. From the People of Rome, honest words.',
    "I come to offer greetings, terms that may prove agreeable, and Rome's honourable pledges if necessary.",
    'Rome desires me to speak the Senate words to you, that we may come to a satisfactory end.',
    "Jupiter's blessings upon our meeting, and let swift Mercury aid in reaching quick agreement!",
    'From the good people of our nation, greetings to our noble friends, and words of great joy to come!',
    'Salutations and friendship from our people, and a proposal for your august consideration!',
    'Honoured greetings unto you. I am sent to speak for the people, for your astute consideration.',
    'Salutations and joyous greetings to you, honoured friend! I have words to speak.',
    'Greetings, good friend, greetings. Let us speak our parts and find agreement!',
    'We graciously extend our greetings and good wishes. Now, to business.',
    'Your people are well known for honesty and manly virtue. That is why I have been sent.',
    'Greetings to you; you are a most worthy diplomat for your people!',
    'I speak with the voice of my people, and am ordered to offer their felicitations at this meeting!',
    'The people have charged me to deliver this proposal. I am not envied in this task.',
    'In the name of a greater people, I speak of worthy things to the unworthy.',
    'Hail. Heed now to the words of the wise, and the rightly proud.',
    'I speak now with the dread voice of the people. Listen carefully, for my words have weight!',
    'I bring word from our people to your ears. You would do well to grasp my full meaning.',
    'I come to do such honour as befits your station. So then, greetings.',
    'I will speak shortly as befits this meeting, and come to the business at hand. Greetings to you.',
    'I am but a servant in this matter, and speak only as I must: greetings to you and yours.',
    'Hail! From my people, I send greetings and a proposal.',
    'Salutations! Let us speak as friends, and conclude any business in mutual satisfaction.',
    'Greetings! I come, as an ambassadorial servant, to seek answers to questions of mutual interest.',
    'I am sent to request your attention in some small matters.',
    'Greetings to you and you people. I bring words that may bring joy to your ears.',
    'Hail! The people greet you, and I am sent to speak on their behalf in many matters.',
    'Greetings and respect from my people. They bring you honest words.',
    'I come to offer greetings, terms that may prove agreeable, and honourable pledges if necessary.',
    'I am instructed to speak desirable words to you, that we may come to a satisfactory end.',
    'May our gods bless this meeting, and lend their aid in reaching quick agreement!',
]

